# Create a Multi-layer fully connected neural network with the following configuration of the hidden layers to classify the digits of the MNIST data base.
Hidden layers configuration:
* Hidden Layer 1 : 300
* Hidden layer 2 : 200
* Hidden layer 3: 100
* Hidden layer 4: 50
* Softmax layer : 10

Train and test the model and print the accuracy. 

In [1]:
import tensorflow as tf
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.examples.tutorials.mnist import input_data

In [18]:
mnist = input_data.read_data_sets('MNIST_data/', one_hot = True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [19]:
x = tf.placeholder(tf.float32,shape=[None,784])
y = tf.placeholder(tf.float32,[None,10])

In [20]:
# Hidden layer 1

w1 = tf.Variable(tf.truncated_normal([784, 300], stddev = 0.1))
b1 = tf.Variable(tf.zeros([300]))

# Input function

input1 = tf.add(tf.matmul(x, w1), b1)

# Activation Function

output1 = tf.nn.relu(input1)

In [21]:
# Hidden layer 2

w2 = tf.Variable(tf.truncated_normal([300, 200], stddev  = 0.1))
b2 = tf.Variable(tf.zeros([200]))

# Input function

input2 = tf.add(tf.matmul(output1, w2), b2)

# Activation Function

output2 = tf.nn.relu(input2)

In [25]:
# Hidden layer 3

w3 = tf.Variable(tf.truncated_normal([200,100],stddev=0.1))
b3 = tf.Variable(tf.zeros([100]))

# Input function

input3 = tf.add(tf.matmul(output2, w3), b3)

# Activation Function

output3 = tf.nn.relu(input3)

In [26]:
# Hidden layer 4

w4 = tf.Variable(tf.truncated_normal([100,50],stddev=0.1))
b4 = tf.Variable(tf.zeros([50]))

# Input function

input4 = tf.add(tf.matmul(output3, w4), b4)

# Activation Function

output4 = tf.nn.relu(input4)

In [27]:
# Hidden layer 5

w5 = tf.Variable(tf.truncated_normal([50,10],stddev=0.1))
b5 = tf.Variable(tf.zeros([10]))

# Input function

input5 = tf.add(tf.matmul(output4, w5), b5)

# Activation Function

output5 = tf.nn.softmax(input5)

In [28]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels = y, logits = output5))

gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.5)

train = gdo.minimize(loss)

In [29]:
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

In [35]:
for step in range(1000):        
        batch_x , batch_y = mnist.train.next_batch(100)        
        sess.run(train,feed_dict={x : batch_x, y : batch_y})

In [36]:
predict = sess.run(output5, feed_dict = {x : mnist.test.images})
predict

array([[4.82198154e-15, 1.13003241e-14, 1.15442350e-10, ...,
        1.00000000e+00, 1.60903935e-19, 1.15026226e-11],
       [2.89773153e-12, 2.48067789e-10, 1.00000000e+00, ...,
        1.20788345e-11, 3.11056194e-12, 5.93022788e-17],
       [1.28299227e-13, 9.99997020e-01, 9.24860046e-07, ...,
        1.73528724e-06, 9.69290648e-10, 7.55309149e-10],
       ...,
       [1.58913884e-22, 7.67091897e-17, 1.22963849e-19, ...,
        2.51069913e-18, 3.95697020e-19, 1.78322851e-13],
       [2.83810302e-11, 1.47930117e-12, 9.11618437e-12, ...,
        2.92329665e-17, 1.80304014e-05, 8.88904367e-11],
       [6.90585242e-15, 2.74377667e-21, 8.98830110e-13, ...,
        3.39597583e-23, 6.89747474e-24, 1.03531746e-26]], dtype=float32)

In [37]:
result = sess.run(tf.argmax(predict, 1))
result

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [38]:
label_number = tf.argmax(mnist.test.labels, 1)
labels = sess.run(label_number)
labels

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [39]:
accuracy_score(result, labels)

0.9589

In [40]:
sess.close()

# ------------------------------------------------- END -------------------------------------------------------